### ISSUE TITLE
`java -jar Bookmaker.jar`で例外が発生する

### ISSUE THREAD

**Issue by exKAZUu** [AI-comp/JavaChallenge2015#9]
```
Exception in thread "main" java.lang.NullPointerException
        at net.aicomp.javachallenge2015.Bookmaker.hasCompleteArgs(Bookmaker.java:131)
        at net.aicomp.javachallenge2015.Bookmaker.main(Bookmaker.java:68)
```

**Comment by junk0612** [comment]
#12 で対応。
